#
# Contains the full stack of bidder3 (not including elk)
#

version: "3"

services:

  zookeeper:
    image: "jplock/zookeeper"
    ports:
      - "2181:2181"

  kafka:
    image: "ches/kafka"
    environment:
      ZOOKEEPER_IP: "zookeeper"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zerospike:
    image: "jacamars/zerospike:pd"
    environment:
      BROKERLIST: "kafka:9092"
      STATUSCHANNEL: "kafka://[$$BROKERLIST]&topic=status"
    ports:
      - "6000:6000"
      - "6001:6001"
      - "6002:6002"
      - "7001:7001"
    #volumes:
    #  - "./cache.db:/cache.db"
    depends_on:
      - kafka
    command: bash -c "./wait-for-it.sh $$BROKERLIST -t 120 && sleep 1; ./zerospike"
    
    
  db:
    image: ploh/mysqlrtb
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rtb4free
      - MYSQL_DATABASE=rtb4free
      - MYSQL_USER=ben
      - MYSQL_PASSWORD=test
      
  web:
    image: ploh/rtbadmin_open
    command: bash -c "./wait_for_it.sh db:3306 --t120; bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      - CUSTOMER_NAME=RTB4FREE
      - RTB4FREE_DATABASE_HOST=db
      - RTB4FREE_DATABASE_PORT=3306
      - RTB4FREE_DATABASE_USERNAME=ben
      - RTB4FREE_DATABASE_PASSWORD=test
      - RTB4FREE_DATABASE_NAME=rtb4free
      - RTB_CROSSTALK_REGION_HOSTS={"US" => "localhost"}
      - ELASTICSEARCH_ENABLE=false
      - ELASTICSEARCH_HOST=
      - ELASTICSEARCH_KIBANA_URL=

  bidder:
    image: "jacamars/rtb4free:pd"
    environment:
      GDPR_MODE: "false"
      
      BROKERLIST: "kafka:9092"
      
      BIDSCHANNEL: "$BIDSCHANNEL"
      WINSCHANNEL: "$WINSCHANNEL"
      REQUESTSCHANNEL: "$REQUESTSCHANNEL"
      CLICKSCHANNEL: "$CLICKSCHANNEL"
      PIXELSCHANNEL: "$PIXELSCHANNEL"
      VIDEOEVENTSCHANNEL: "$VIDEOEVENTSCHANNEL"
      POSTBACKEVENTSCHANNEL: "$POSTBACKEVENTSCHANNEL"
      STATUSCHANNEL: "$STATUSCHANNEL"
      REASONSCHANNEL: "$REASONSCHANNEL"  
      LOGCHANNEL: "$LOGCHANNEL"
         
      BROKERLIST: "kafka:9092"
      
      PUBSUB: "zerospike"
      EXTERNAL: "http://localhost:8080"
      ACCOUNTING: "accountingsystem"
      
      S3BUCKET: ""
      S3REGION: ""
      S3SECRETKEY: ""
      S3ACCESSKEY: ""
      
      AWSACCESSKEY: ""
      AWSSECRETKEY: ""
      AWSREGION: ""
      
      GOOGLE_EKEY: ""
      GOOGLE_IKEY: ""
      OPENX_EKEY: ""
      OPENX_IKEY: ""
      ADX_EKEY:   ""
      ADX_IKEY:   ""
      BIDSWITCH_ID: "1234"
      ADMINPORT: "0"
    ports:
      - "8080:8080"
      - "8155:8155"
      - "7379:7379"
      - "7000:7000"
    depends_on:
      - kafka
      - zerospike
    command: bash -c "./wait-for-it.sh $$BROKERLIST -t 120 && ./wait-for-it.sh zerospike:6000 -t 120 && sleep 1; ./rtb4free"

